### ISSUE TITLE
Build initial skeleton

### ISSUE THREAD

**Issue by nicholaswmin** [TheProfs/pdf-to-image#1]
*Details Pending*

## Todos

- [x] Expose a method that returns all pages of pdf
- [x] Allow passing an array of page numbers to print
- [x] Create thumbnails for each image
- [x] Transpile to ES5
